language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zaki-sh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zaki-sh/react-test npm test

after_success:
  - docker build -t zaki1404/multi-client ./client
  - docker build -t zaki1404/multi-nginx ./nginx
  - docker build -t zaki1404/multi-server ./server
  - docker build -t zaki1404/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERID" --password-stdin
  # Take those images and push to docker hub
  - docker push zaki1404/multi-client
  - docker push zaki1404/multi-nginx
  - docker push zaki1404/multi-server
  - docker push zaki1404/multi-worker
